data:
  aug_strength: standard
  augment: true
  batch_size: 32
  clahe_clip_limit: 2.0
  clahe_tile_grid: !!python/tuple
  - 8
  - 8
  class_names: null
  cutmix_alpha: 0.0
  display_name: default
  drop_last: true
  frame_sample_rate: 1
  hf_config: null
  hf_repo_id: null
  hf_split_mapping:
    test: test
    train: train
    val: validation
  image_size: 224
  image_size_val: 224
  is_multi_label: false
  mean: !!python/tuple
  - 0.485
  - 0.456
  - 0.406
  mixup_alpha: 0.0
  name: default
  num_classes: 1000
  num_frames: 8
  num_workers: 4
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 2
  rand_augment: false
  root_dir: null
  shuffle_train: true
  source: local
  std: !!python/tuple
  - 0.229
  - 0.224
  - 0.225
  task: classification
  test_subdir: test
  train_subdir: train
  tv_dataset_name: null
  tv_root: null
  use_clahe: false
  val_subdir: val
